-- ==========================================================================
-- PHASE 6 BOOTSTRAP - SCHEMA PLUS THE PREDICTIONS ALREADY WRITTEN
-- ==========================================================================
--
-- GENERATED by scripts/phase6_backfill_supabase.py --sql.
-- Do not edit: regenerate it. Safe to run more than once.
--
-- Paste the whole file into the Supabase SQL editor and run it. It does
-- two things, and the second one is why capture is currently blocked:
--
--   1. creates the three tables, their constraints, the RLS policies and
--      the live_log_coverage view;
--
--   2. inserts the 10 predictions already in the committed mirror.
--      public.results.match_id is a foreign key onto public.predictions,
--      so until these rows exist, phase6_capture_results.py cannot insert
--      a single scoreline - the foreign key refuses it.
--
-- These rows are COPIED, not recomputed. Each was written before its
-- matchweek's first kickoff and is timestamped in git; this file only
-- catches the dashboard's copy up to the record.
--
-- Source   live_log/phase6_live_predictions.csv
-- Freeze   b36befd3e13d5f7f5d9b0af83b7db819e86d7b13e6fdcab4c55db0599fd248f6
-- Rows     10, chain verified contiguous from genesis
-- ==========================================================================


-- --------------------------------------------------------------------------
-- PART 1 OF 2 - THE SCHEMA, verbatim from ops/supabase_live_log.sql
-- --------------------------------------------------------------------------

-- ============================================================================
-- PHASE 6 - THE LIVE PREDICTION LOG, SUPABASE SCHEMA AND RLS
-- ============================================================================
--
-- Governed by PHASE6_LIVE_LOG_PROTOCOL.txt section 9, which is governed by
-- PHASE6_HOLDOUT_FREEZE.txt (sha256 b36befd3...248f6) and
-- PHASE6_CUTOFF_PIN.txt.
--
-- THE SERVICE KEY IS NOT IN THIS FILE AND IS NOT IN THIS REPOSITORY. The
-- generator reads SUPABASE_URL and SUPABASE_SERVICE_KEY from the environment.
--
-- WHAT THIS IS NOT. Supabase is the dashboard's copy. The PRIMARY record is
-- live_log/phase6_live_predictions.csv in git, because git is what timestamps
-- a row in a way the operator cannot backdate (L9.4). If this database is
-- lost, the evidence is not.
--
-- Apply with:  psql "$SUPABASE_DB_URL" -f ops/supabase_live_log.sql
--         or:  paste into the Supabase SQL editor
--
-- Idempotent: safe to re-run.
-- ============================================================================


-- ============================================================
-- 1. predictions
-- ============================================================
--
-- One row per match, written ONCE, before that matchweek's first kickoff.
-- Never updated, never deleted, never regenerated (L1.4, L3.1).

create table if not exists public.predictions (
    -- L3.3. season + home + away. NOT date-based, because L3.1 keeps a
    -- postponed match's original prediction and the date moves underneath it.
    match_id            text primary key,

    season              text        not null default '2026-2027',
    round_id            integer     not null,
    matchweek_label     integer,                -- informational only, L1.3

    scheduled_date      date        not null,
    scheduled_kickoff   text,

    home_team           text        not null,
    away_team           text        not null,

    -- L1.2. The state window was every completed match with date < this.
    state_cutoff_date   date        not null,

    -- The claim this table exists to make: written at this instant, and the
    -- first kickoff of the round was strictly after it.
    generated_at_utc    timestamptz not null,

    p_home              double precision not null,
    p_draw              double precision not null,
    p_away              double precision not null,
    lambda_home         double precision not null,
    lambda_away         double precision not null,
    rho                 double precision not null,

    fit_matches         integer     not null,
    home_has_history    boolean     not null,
    away_has_history    boolean     not null,

    -- Which frozen documents were in force. A row that cannot name its own
    -- governing texts is not evidence of anything.
    freeze_sha          text        not null,
    pin_sha             text        not null,
    protocol_sha        text        not null,

    -- L4.2. The chain. prev_hash of the first row is sixty-four zeroes.
    prev_hash           text        not null,
    row_hash            text        not null unique,

    inserted_at         timestamptz not null default now(),

    -- Cheap invariants, asserted in the database rather than trusted from the
    -- writer. The writer already checks them; two independent checks of the
    -- same claim is the project's standing pattern.
    constraint predictions_probabilities_sum
        check (abs(p_home + p_draw + p_away - 1.0) < 1e-9),
    constraint predictions_probabilities_range
        check (p_home > 0 and p_draw > 0 and p_away > 0),
    constraint predictions_rates_positive
        check (lambda_home > 0 and lambda_away > 0),
    -- L1.2, in the schema: the state cutoff precedes the fixture it predicts.
    constraint predictions_cutoff_precedes_fixture
        check (state_cutoff_date <= scheduled_date),
    constraint predictions_hashes_are_sha256
        check (row_hash ~ '^[0-9a-f]{64}$' and prev_hash ~ '^[0-9a-f]{64}$')
);

create index if not exists predictions_round_idx
    on public.predictions (round_id, scheduled_date);


-- ============================================================
-- 2. results
-- ============================================================
--
-- Populated after a matchweek, from the E0 file the pin declares as the
-- 2026-27 spine (P7.2). Scorelines only - no metric is computed here, and
-- L5.1 keeps the official result in phase6_score_holdout.py.

create table if not exists public.results (
    match_id            text primary key
        references public.predictions (match_id) on delete restrict,

    season              text        not null default '2026-2027',

    -- The date actually PLAYED, which under L3.1 may differ from the
    -- scheduled_date the prediction was written against.
    played_date         date        not null,

    home_goals          integer     not null check (home_goals >= 0),
    away_goals          integer     not null check (away_goals >= 0),
    result              char(1)     not null check (result in ('H', 'D', 'A')),

    -- L3.4. played_date - state_cutoff_date. Populated at capture, because at
    -- generation the date played is not yet known.
    state_age_days      integer     not null,
    -- L3.5. Pre-declared at 10 days, from the development distribution.
    is_stale            boolean     not null,

    -- L2. True when no pre-kickoff prediction existed for this match. Such a
    -- match is excluded from the LOG's figures and is never excluded from the
    -- holdout, which remains a date rule in a frozen document (L2.2).
    contaminated        boolean     not null default false,

    source_sha256       text        not null,
    captured_at_utc     timestamptz not null,
    inserted_at         timestamptz not null default now(),

    constraint results_result_matches_goals check (
        (home_goals > away_goals and result = 'H') or
        (home_goals = away_goals and result = 'D') or
        (home_goals < away_goals and result = 'A')
    )
);


-- ============================================================
-- 3. market
-- ============================================================
--
-- B3.3 fixes the primary book as BET365 CLOSING. B4.1 fixes the de-vig as
-- proportional. Both were chosen in PHASE5_MARKET_PREDECLARATION.txt before
-- any score existed, and neither is reconsidered here.
--
-- PINNACLE IS ABSENT FROM THE 2026-27 FILE (SW5-PSC) AND NO OTHER BOOK IS
-- PROMOTED TO REPLACE IT. REPORT.md section 7 records that as a reduction in
-- scope. Choosing a sensitivity instrument after seeing which one survived is
-- selection on the very thing a sensitivity exists to test.

create table if not exists public.market (
    match_id            text primary key
        references public.predictions (match_id) on delete restrict,

    season              text        not null default '2026-2027',
    book                text        not null default 'B365C',

    odds_home           double precision not null check (odds_home > 1.0),
    odds_draw           double precision not null check (odds_draw > 1.0),
    odds_away           double precision not null check (odds_away > 1.0),

    -- B4.1, proportional. Computed by phase5_market_benchmark.devig_proportional,
    -- imported rather than reimplemented.
    p_home              double precision not null,
    p_draw              double precision not null,
    p_away              double precision not null,
    overround           double precision not null,

    source_sha256       text        not null,
    captured_at_utc     timestamptz not null,
    inserted_at         timestamptz not null default now(),

    constraint market_probabilities_sum
        check (abs(p_home + p_draw + p_away - 1.0) < 1e-9),
    constraint market_book_is_the_declared_primary
        check (book = 'B365C')
);


-- ============================================================
-- 4. RLS
-- ============================================================
--
-- NO POLICY FOR INSERT, UPDATE OR DELETE. Under RLS, no policy means denied,
-- and that absence is the mechanism rather than an omission. SELECT is the only
-- verb any RLS role is granted.
--
-- -----------------------------------------------------------------------------
-- AMENDED 2026-09-13. THE EARLIER VERSION OF THIS SECTION CONTRADICTED ITS OWN
-- GOVERNING PROTOCOL, AND ON A PUBLIC DEPLOYMENT THAT WAS EXPLOITABLE.
--
-- It carried three policies of the form
--
--     create policy predictions_append on public.predictions
--         for insert to anon, authenticated with check (true);
--
-- while PHASE6_LIVE_LOG_PROTOCOL.txt L9.2 declares, in terms:
--
--     "The anon key is SELECT-only and is what the frontend uses. Writes come
--      from the local generator under the service key."
--
-- and L9.5 claims:
--
--     "RLS protects the log from the frontend and from anyone holding the anon
--      key."
--
-- Both statements were FALSE as the SQL stood. The anon key is compiled into
-- the browser bundle of a public site by design, so "anyone holding the anon
-- key" meant anyone at all, and `with check (true)` let them append arbitrary
-- rows to the prediction log, the results and the market prices.
--
-- The chain and the git mirror would have caught it - an injected row cannot
-- produce a prev_hash that links, and live_log/phase6_live_predictions.csv is
-- the primary record under L9.4 - so the EVIDENCE was never at risk. The
-- dashboard was: it would have rendered the injected rows as predictions.
--
-- WHY REMOVING THE POLICIES COSTS NOTHING. The only writer is the generator,
-- and it writes under the service role, which bypasses RLS entirely (section 5
-- below, and L9.5). It never needed an RLS policy to insert. Neither does
-- ops/supabase_bootstrap.sql, which is pasted into the Supabase SQL editor and
-- runs as a privileged role, nor scripts/phase6_backfill_supabase.py, which
-- also uses the service key.
--
-- So this is the implementation being corrected to match the declared design,
-- not the design being changed. The protocol did not move; the SQL now agrees
-- with it.
-- -----------------------------------------------------------------------------

alter table public.predictions enable row level security;
alter table public.results     enable row level security;
alter table public.market      enable row level security;

-- Belt as well as braces: revoke the verbs outright, so a future permissive
-- policy added by accident still has no privilege to ride on.
revoke update, delete, truncate on public.predictions from anon, authenticated;
revoke update, delete, truncate on public.results     from anon, authenticated;
revoke update, delete, truncate on public.market      from anon, authenticated;

-- ---- read: the frontend, anon key, SELECT only -----------------------------
drop policy if exists predictions_read on public.predictions;
create policy predictions_read on public.predictions
    for select to anon, authenticated using (true);

drop policy if exists results_read on public.results;
create policy results_read on public.results
    for select to anon, authenticated using (true);

drop policy if exists market_read on public.market;
create policy market_read on public.market
    for select to anon, authenticated using (true);

-- ---- append: NOT granted through RLS ----------------------------------------
--
-- Dropped rather than merely absent, so that re-running this file on a database
-- that already has the 2026-09-13 amendment's predecessor REMOVES the policies
-- instead of leaving them standing. An idempotent file that cannot undo the
-- thing it was amended to undo is not idempotent in the way that matters.
drop policy if exists predictions_append on public.predictions;
drop policy if exists results_append on public.results;
drop policy if exists market_append on public.market;

-- Belt and braces on the same point: take the grant away too, so a future
-- permissive policy added by accident has no privilege to ride on.
revoke insert on public.predictions from anon, authenticated;
revoke insert on public.results     from anon, authenticated;
revoke insert on public.market      from anon, authenticated;

-- NO INSERT, UPDATE OR DELETE POLICY ON ANY OF THE THREE TABLES.
-- This blank space is the immutability guarantee. Do not fill it in.


-- ============================================================
-- 5. WHAT RLS DOES NOT DO, STATED BECAUSE IT IS A REAL LIMIT
-- ============================================================
--
-- L9.5. THE SERVICE ROLE BYPASSES RLS ENTIRELY. Everything above protects the
-- log from the frontend and from anyone holding the anon key - which, since the
-- 2026-09-13 amendment in section 4, is now actually true. It does NOT protect
-- it from the key the generator itself writes with.
--
-- So the immutability of this log rests on three things, and RLS is only one:
--
--   1. the generator's own refusal to write a match_id that already exists,
--      which raises rather than skipping quietly (L1.4);
--   2. the L4 row-hash chain, which makes an edit, a deletion or a reorder
--      detectable after the fact by anyone holding the file;
--   3. the mirror in git, which is the primary record and is timestamped by
--      something other than the operator's own database.
--
-- A reader who trusts only this file should trust (2) and (3).

-- ============================================================
-- 6. THE INTEGRITY VIEW THE DASHBOARD SHOULD READ
-- ============================================================
--
-- So that a dashboard cannot show a running figure without also being able to
-- show how much of the holdout the log actually covers (L2.4, L5.2).

create or replace view public.live_log_coverage as
select
    (select count(*) from public.predictions)                        as predictions_written,
    (select count(*) from public.results)                            as results_captured,
    (select count(*) from public.results where contaminated)         as contaminated_matches,
    (select count(*) from public.results where is_stale)             as stale_matches,
    (select min(scheduled_date) from public.predictions)             as first_predicted,
    (select max(scheduled_date) from public.predictions)             as last_predicted,
    -- Informal, and the view says so in its own column name.
    'INFORMAL - the official 2026-27 result is phase6_score_holdout.py run '
    'once at season end (L5.1)'                                      as authority_note;

grant select on public.live_log_coverage to anon, authenticated;


-- --------------------------------------------------------------------------
-- PART 2 OF 2 - THE PREDICTIONS
-- --------------------------------------------------------------------------

insert into public.predictions (
    match_id,
    season,
    round_id,
    matchweek_label,
    scheduled_date,
    scheduled_kickoff,
    home_team,
    away_team,
    state_cutoff_date,
    generated_at_utc,
    p_home,
    p_draw,
    p_away,
    lambda_home,
    lambda_away,
    rho,
    fit_matches,
    home_has_history,
    away_has_history,
    freeze_sha,
    pin_sha,
    protocol_sha,
    prev_hash,
    row_hash
) values
    -- Aston Villa v Nottingham, 2026-09-12
    ('2026-2027_Aston-Villa_Nottingham', '2026-2027', 1, 4, '2026-09-12', '15:00', 'Aston Villa', 'Nottingham', '2026-09-12', '2026-09-11T19:21:39Z', 0.37301039662552904, 0.30414183014779933, 0.32284777322667163, 1.298014552575443, 1.192885876807715, -0.13244300576120613, 1930, true, true, 'b36befd3e13d5f7f5d9b0af83b7db819e86d7b13e6fdcab4c55db0599fd248f6', 'be9b1b084db57a3bef2e71f83a04c9d89299cbe1599b936f0615a69b1c266e15', '3ee62e3df3974d141979759e5e2fd14831b229d77c940f6fd3a53c7f0b5d4b8a', '0000000000000000000000000000000000000000000000000000000000000000', '9f3ac588c1fbb60e7a8fd7344bed1b94a412eda7fac2d68c198bc57f2303559d'),
    -- Bournemouth v Brentford, 2026-09-12
    ('2026-2027_Bournemouth_Brentford', '2026-2027', 1, 4, '2026-09-12', '15:00', 'Bournemouth', 'Brentford', '2026-09-12', '2026-09-11T19:21:39Z', 0.42522812195964205, 0.28700755934046634, 0.2877643186998917, 1.498593303210512, 1.1993171412735888, -0.13244300576120613, 1930, true, true, 'b36befd3e13d5f7f5d9b0af83b7db819e86d7b13e6fdcab4c55db0599fd248f6', 'be9b1b084db57a3bef2e71f83a04c9d89299cbe1599b936f0615a69b1c266e15', '3ee62e3df3974d141979759e5e2fd14831b229d77c940f6fd3a53c7f0b5d4b8a', '9f3ac588c1fbb60e7a8fd7344bed1b94a412eda7fac2d68c198bc57f2303559d', 'e59df9d5bad697a7de7def253d33847155f988173c91e3de6b79a0efa7d56c71'),
    -- Chelsea v Hull, 2026-09-12
    ('2026-2027_Chelsea_Hull', '2026-2027', 1, 4, '2026-09-12', '15:00', 'Chelsea', 'Hull', '2026-09-12', '2026-09-11T19:21:39Z', 0.5484001154140404, 0.2611111616804913, 0.1904887229054685, 1.7834218273637603, 0.9780187206006373, -0.13244300576120613, 1930, true, true, 'b36befd3e13d5f7f5d9b0af83b7db819e86d7b13e6fdcab4c55db0599fd248f6', 'be9b1b084db57a3bef2e71f83a04c9d89299cbe1599b936f0615a69b1c266e15', '3ee62e3df3974d141979759e5e2fd14831b229d77c940f6fd3a53c7f0b5d4b8a', 'e59df9d5bad697a7de7def253d33847155f988173c91e3de6b79a0efa7d56c71', '2de530dfd296489fab5d8acc0f5eae01c269b6de389c4f0509d10544bc1f8396'),
    -- Crystal Palace v Ipswich Town, 2026-09-12
    ('2026-2027_Crystal-Palace_Ipswich-Town', '2026-2027', 1, 4, '2026-09-12', '15:00', 'Crystal Palace', 'Ipswich Town', '2026-09-12', '2026-09-11T19:21:39Z', 0.5763335309569086, 0.2195548965621015, 0.20411157248098988, 2.2647824191798964, 1.3188339930966062, -0.13244300576120613, 1930, true, true, 'b36befd3e13d5f7f5d9b0af83b7db819e86d7b13e6fdcab4c55db0599fd248f6', 'be9b1b084db57a3bef2e71f83a04c9d89299cbe1599b936f0615a69b1c266e15', '3ee62e3df3974d141979759e5e2fd14831b229d77c940f6fd3a53c7f0b5d4b8a', '2de530dfd296489fab5d8acc0f5eae01c269b6de389c4f0509d10544bc1f8396', '923ed096e99dcdf855250834c529dc742129238fecdd445a38f72e97a4893561'),
    -- Liverpool v Fulham, 2026-09-12
    ('2026-2027_Liverpool_Fulham', '2026-2027', 1, 4, '2026-09-12', '15:00', 'Liverpool', 'Fulham', '2026-09-12', '2026-09-11T19:21:39Z', 0.5901928928461345, 0.23385804429430535, 0.17594906285956016, 2.0561014594534828, 1.0613906802805435, -0.13244300576120613, 1930, true, true, 'b36befd3e13d5f7f5d9b0af83b7db819e86d7b13e6fdcab4c55db0599fd248f6', 'be9b1b084db57a3bef2e71f83a04c9d89299cbe1599b936f0615a69b1c266e15', '3ee62e3df3974d141979759e5e2fd14831b229d77c940f6fd3a53c7f0b5d4b8a', '923ed096e99dcdf855250834c529dc742129238fecdd445a38f72e97a4893561', '0ca8815882864407f8b9830a9708f9bc4dc27e1b22cc71ce912209e94f645c2b'),
    -- Tottenham v Everton, 2026-09-12
    ('2026-2027_Tottenham_Everton', '2026-2027', 1, 4, '2026-09-12', '17:30', 'Tottenham', 'Everton', '2026-09-12', '2026-09-11T19:21:39Z', 0.2498166676005715, 0.31031125140549926, 0.4398720809939293, 0.9605919446140725, 1.348610870527354, -0.13244300576120613, 1930, true, true, 'b36befd3e13d5f7f5d9b0af83b7db819e86d7b13e6fdcab4c55db0599fd248f6', 'be9b1b084db57a3bef2e71f83a04c9d89299cbe1599b936f0615a69b1c266e15', '3ee62e3df3974d141979759e5e2fd14831b229d77c940f6fd3a53c7f0b5d4b8a', '0ca8815882864407f8b9830a9708f9bc4dc27e1b22cc71ce912209e94f645c2b', '49dffac7f9fbcbc6d75fcc4f83807069f6477bf257616a059f7ad4cdfdf341d0'),
    -- Sunderland v Arsenal, 2026-09-12
    ('2026-2027_Sunderland_Arsenal', '2026-2027', 1, 4, '2026-09-12', '20:00', 'Sunderland', 'Arsenal', '2026-09-12', '2026-09-11T19:21:39Z', 0.1359568110257159, 0.2977312056376611, 0.566311983336623, 0.5874149556789713, 1.4444066549397891, -0.13244300576120613, 1930, true, true, 'b36befd3e13d5f7f5d9b0af83b7db819e86d7b13e6fdcab4c55db0599fd248f6', 'be9b1b084db57a3bef2e71f83a04c9d89299cbe1599b936f0615a69b1c266e15', '3ee62e3df3974d141979759e5e2fd14831b229d77c940f6fd3a53c7f0b5d4b8a', '49dffac7f9fbcbc6d75fcc4f83807069f6477bf257616a059f7ad4cdfdf341d0', '891e794a12c6cbe52092b89f1d4be3d8a5a21c7c4b0f903a6e3e1c85d634a152'),
    -- Coventry v Brighton, 2026-09-13
    ('2026-2027_Coventry_Brighton', '2026-2027', 1, 4, '2026-09-13', '14:00', 'Coventry', 'Brighton', '2026-09-12', '2026-09-11T19:21:39Z', 0.30467517227054686, 0.28806646868140157, 0.4072583590480517, 1.2420766314417202, 1.4653908373628604, -0.13244300576120613, 1930, true, true, 'b36befd3e13d5f7f5d9b0af83b7db819e86d7b13e6fdcab4c55db0599fd248f6', 'be9b1b084db57a3bef2e71f83a04c9d89299cbe1599b936f0615a69b1c266e15', '3ee62e3df3974d141979759e5e2fd14831b229d77c940f6fd3a53c7f0b5d4b8a', '891e794a12c6cbe52092b89f1d4be3d8a5a21c7c4b0f903a6e3e1c85d634a152', 'dd6c2841a5ee3626f0a70510e3968f922d3755b077fe13ec93ce51fdef464c0a'),
    -- Manchester Utd v Manchester City, 2026-09-13
    ('2026-2027_Manchester-Utd_Manchester-City', '2026-2027', 1, 4, '2026-09-13', '16:30', 'Manchester Utd', 'Manchester City', '2026-09-12', '2026-09-11T19:21:39Z', 0.2928029845556577, 0.2472515183008351, 0.4599454971435073, 1.496216560123327, 1.9005170572724575, -0.13244300576120613, 1930, true, true, 'b36befd3e13d5f7f5d9b0af83b7db819e86d7b13e6fdcab4c55db0599fd248f6', 'be9b1b084db57a3bef2e71f83a04c9d89299cbe1599b936f0615a69b1c266e15', '3ee62e3df3974d141979759e5e2fd14831b229d77c940f6fd3a53c7f0b5d4b8a', 'dd6c2841a5ee3626f0a70510e3968f922d3755b077fe13ec93ce51fdef464c0a', 'ea0cd8be8345dbf8ffbea96a23c45c0f4e622ca79dd9b720aaef0778d8027b60'),
    -- Leeds United v Newcastle, 2026-09-14
    ('2026-2027_Leeds-United_Newcastle', '2026-2027', 1, 4, '2026-09-14', '20:00', 'Leeds United', 'Newcastle', '2026-09-12', '2026-09-11T19:21:39Z', 0.4165181421630724, 0.29335946409736585, 0.29012239373956167, 1.4398194685158703, 1.1688339051425047, -0.13244300576120613, 1930, true, true, 'b36befd3e13d5f7f5d9b0af83b7db819e86d7b13e6fdcab4c55db0599fd248f6', 'be9b1b084db57a3bef2e71f83a04c9d89299cbe1599b936f0615a69b1c266e15', '3ee62e3df3974d141979759e5e2fd14831b229d77c940f6fd3a53c7f0b5d4b8a', 'ea0cd8be8345dbf8ffbea96a23c45c0f4e622ca79dd9b720aaef0778d8027b60', '84e2b736ea35d9f00bfb06f92cebc84f7b5763d796593f48b2e3b4e1ef45db34')
on conflict (match_id) do nothing;


-- --------------------------------------------------------------------------
-- CHECK IT LANDED
-- --------------------------------------------------------------------------

select * from public.live_log_coverage;

-- predictions_written should read 10. Once it does, capture is
-- unblocked and results can be inserted against these match_ids.
